[screen]
width = 5120
height = 1440
title = "App title"
back_colour = [0, 0, 0]

[loguru]
level = "DEBUG"

[sprite]
random_size = true
min_size = 6
max_size = 100
fixed_size = 24

base_speed = 16
min_speed = 6
max_speed = 24

min_energy = 50.0
max_energy = 100.0
energy_scale = 0.0008